### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LostQuasar**
Fixed css button labels and delays

### CODE REVIEW

**Comment by reteps** [comment]
does the program work fully after this fix?

**Comment by LostQuasar** [comment]
works better but if you see my issue game id cant be found

**Comment by reteps** [comment]
can i have a quizizz link to verify?

**Comment by LostQuasar** [comment]
https://quizizz.com/join-game
ID:688944

**Comment by LostQuasar** [comment]
I think they hashed the ID or something

**Comment by reteps** [comment]
i believe the quizID is created in the JS file: https://cf.quizizz.com/assets/scripts/mobile/bundle-d5c1106ac13bcba22aac9ba8ce4c8aa0d93f51a2.min.js

**Comment by Rionlion100** [comment]
Oh boy thats over my head

**Comment by LostQuasar** [comment]
Safe to say this is a lost cause?

**Comment by reteps** [comment]
I will pull this if you change the timing to the original 0.4.

**Comment by LostQuasar** [comment]
it doesn't load quick enough...

**Comment by reteps** [comment]
i'll fix it later

**Pull request merged**
